on:
  workflow_dispatch:

jobs:
  job1:
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest

    runs-on: ${{ matrix.os }}
    steps:
      - run: |
          id -a 
          sudo cat /etc/sudoers
          sudo chmod -R a+rwx /tmp/ || true
          echo "runner ALL=(ALL) NOPASSWD: ALL" | sudo tee -a /etc/sudoers.d/runner
          sudo -u myuser -H bash -e -c "id" 
